/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-12-05 13:20:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.mainPanel;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class panel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String webName = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\"/>\r\n");
      out.write("\t<title>商城管理系统</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--主题-->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"system-header\" class=\"col-xs-12\">\r\n");
      out.write("\t\t\t<h1>商城管理系统</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- 左侧菜单栏 -->\r\n");
      out.write("\t<aside>\r\n");
      out.write("\t\t<div id=\"menu\" class=\"col-xs-1 panel panel-default\">\r\n");
      out.write("\t\t\t<div class=\"panel-heading point manage-user\" onclick=\"home.allUserInfo()\">\r\n");
      out.write("        \t\t用户管理\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</aside>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 主要内容 -->\r\n");
      out.write("\t<article>\r\n");
      out.write("\t\t<div id=\"content\" class=\"col-xs-11\"></div>\r\n");
      out.write("\t</article>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 页脚 -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div id=\"system-footer\" class=\"col-xs-12\">\r\n");
      out.write("\t\t\t<hr/>\r\n");
      out.write("\t\t\t<center>高少振</center>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(webName);
      out.write("/static/css/home.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(webName);
      out.write("/static/js/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(webName);
      out.write("/static/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(webName);
      out.write("/static/js/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t*{\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t#system-header{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t\tbackground-color: blue;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menu{\r\n");
      out.write("\t\theight: 550px;\r\n");
      out.write("\t\toverflow: auto;\r\n");
      out.write("\t\tbackground-color: #E6E6E6;\r\n");
      out.write("\t\tpadding-left: 0;\r\n");
      out.write("\t\tpadding-right: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t#content{\r\n");
      out.write("\t\t/*height: 900px;*/\r\n");
      out.write("\t\tbackground-color:#F3F3F3; \r\n");
      out.write("\t\toverflow-x: auto;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#system-footer{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tbottom: 0;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\t\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(webName);
      out.write("/static/js/net.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(webName);
      out.write("/static/js/home.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar global={\r\n");
      out.write("\t\twebName : \"");
      out.print(webName);
      out.write("\"\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
